server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: final-project-be
  ai:
    openai:
      enabled: false
      chat:
        enabled: false

    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5:7b-instruct
        options:
          temperature: 0.2
          num-ctx: 2048
          num-predict: 256

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
  datasource:
    url: jdbc:postgresql://103.101.161.248:5432/mydb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  kafka:
    bootstrap-servers: broker:9092
    consumer:
      group-id: email-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: totruongchinh@gmail.com
    password: ytwq fzvg jozz tybk   # App Password
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  sql:
    init:
      platform: postgres

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: admin@123
  bucket: mybucket

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG

